version: '3'

services:
  db:
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    ports:
      - '5432:5432'
    restart: unless-stopped